In [3]:
# ABC tech IT
import numpy as np

In [5]:
# TASK 1
emp_id_for_HR = np.arange(1,4,1)
emp_id_for_HR

array([1, 2, 3])

In [3]:
emp_id_for_IT = np.arange(4,19,1)
emp_id_for_IT

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [4]:
emp_id_for_FINANCE = np.arange(19,24,1)
emp_id_for_FINANCE

array([19, 20, 21, 22, 23])

In [5]:
emp_id_for_SALES = np.arange(24,31,1)
emp_id_for_SALES

array([24, 25, 26, 27, 28, 29, 30])

In [6]:
# TASK 2
salary_HR = np.array([50,60,57])
salary_HR

array([50, 60, 57])

In [7]:
salary_IT = np.full(15 , 67)  #creates a NumPy array with 15 elements, each element having the value 67.
salary_IT

array([67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67])

In [8]:
salary_FINANCE = np.array([60,65,50,70,87])
salary_FINANCE

array([60, 65, 50, 70, 87])

In [9]:
salary_SALES = np.array([50,60,65,90,56,65,71])
salary_SALES

array([50, 60, 65, 90, 56, 65, 71])

In [10]:
# TASK 3
print("\nAverage salary of employees in HR department is: " ,salary_HR.mean())
print("\nAverage salary of employees in IT department is: " ,salary_IT.mean()) 
print("\nAverage salary of employees in FINANCE department is: " ,salary_FINANCE.mean()) 
print("\nAverage salary of employees in SALES department is: " ,salary_SALES.mean()) 


Average salary of employees in HR department is:  55.666666666666664

Average salary of employees in IT department is:  67.0

Average salary of employees in FINANCE department is:  66.4

Average salary of employees in SALES department is:  65.28571428571429


In [11]:
department_expenses = {
    'HR': salary_HR.mean(),
    'IT': salary_IT.mean(),
    'FINANCE': salary_FINANCE.mean(),
    'SALES': salary_SALES.mean()}

max_department = max(department_expenses, key=department_expenses.get)
max_avg_salary = department_expenses[max_department]

# printing Department with the highest average salary expense
print("\nDepartment with the highest average salary expense:",max_department)


Department with the highest average salary expense: IT


In [14]:
# TASK 4
#    
# Finding the highest salaries in HR departments
highest_salary_HR = np.max(salary_HR)             
   # Finding the highest salaries in FINANCE departments
highest_salary_FINANCE = np.max(salary_FINANCE)

print("\nHighest Salaries in HR department:",highest_salary_HR)
print("\nHighest Salaries in FINANCE department:",highest_salary_FINANCE)


Highest Salaries in HR department: 60

Highest Salaries in FINANCE department: 87


# TASK 5

In [15]:
   #salaries in  salary_IT*0.5 + salary_IT
joining_bonus = salary_IT*0.5 + salary_IT
updated_salaries_IT = joining_bonus
updated_salaries_IT

array([100.5, 100.5, 100.5, 100.5, 100.5, 100.5, 100.5, 100.5, 100.5,
       100.5, 100.5, 100.5, 100.5, 100.5, 100.5])