# University Admission Decision

In [4]:
import numpy as np

# TASK 1

In [3]:
file_name = r'C:\Users\user\Downloads\DS1_C4_S1_AdmissionPredict_Data_Practice__1_.csv'  #'r',indicates a "raw string literal"
adm_data = np.genfromtxt(file_name ,delimiter=',',skip_header=1)
adm_data

array([[  1.  , 337.  , 118.  , ...,   9.65,   1.  ,   0.92],
       [  2.  , 324.  , 107.  , ...,   8.87,   1.  ,   0.76],
       [  3.  , 316.  , 104.  , ...,   8.  ,   1.  ,   0.72],
       ...,
       [398.  , 330.  , 116.  , ...,   9.45,   1.  ,   0.91],
       [399.  , 312.  , 103.  , ...,   8.78,   0.  ,   0.67],
       [400.  , 333.  , 117.  , ...,   9.66,   1.  ,   0.95]])

# TASK 2

In [5]:
#Display the GRE score of all students
GRE_score = adm_data[:,1]  #taking all rows and second column as GRE_score
GRE_score

array([337., 324., 316., 322., 314., 330., 321., 308., 302., 323., 325.,
       327., 328., 307., 311., 314., 317., 319., 318., 303., 312., 325.,
       328., 334., 336., 340., 322., 298., 295., 310., 300., 327., 338.,
       340., 331., 320., 299., 300., 304., 307., 308., 316., 313., 332.,
       326., 322., 329., 339., 321., 327., 313., 312., 334., 324., 322.,
       320., 316., 298., 300., 311., 309., 307., 304., 315., 325., 325.,
       327., 316., 318., 328., 332., 336., 321., 314., 314., 329., 327.,
       301., 296., 294., 312., 340., 320., 322., 340., 319., 315., 317.,
       314., 316., 318., 299., 298., 301., 303., 304., 306., 331., 332.,
       323., 322., 312., 314., 317., 326., 316., 329., 338., 331., 304.,
       305., 321., 301., 320., 311., 310., 299., 290., 296., 327., 335.,
       334., 310., 308., 301., 300., 323., 319., 326., 333., 339., 303.,
       309., 323., 333., 314., 312., 316., 326., 318., 329., 332., 331.,
       340., 325., 320., 315., 326., 339., 311., 33

# TASK 3

In [6]:
condition = GRE_score[GRE_score>320] #putting condition on GRE_score
print("\nTotal No.of Students with GRE_score greater the 320 is:",condition.size)


Total No.of Students with GRE_score greater the 320 is: 163


# TASK 4

In [7]:
TOEFL_score = adm_data[:,2]    # calliing TOFEL_score Column as 1D
Chance_of_Admit = adm_data[:,8] #calling Chance_of_Admit column as 1D

In [8]:
TOEFL_score

array([118., 107., 104., 110., 103., 115., 109., 101., 102., 108., 106.,
       111., 112., 109., 104., 105., 107., 106., 110., 102., 107., 114.,
       116., 119., 119., 120., 109.,  98.,  93.,  99.,  97., 103., 118.,
       114., 112., 110., 106., 105., 105., 108., 110., 105., 107., 117.,
       113., 110., 114., 119., 110., 111.,  98., 100., 116., 112., 110.,
       103., 102.,  99.,  99., 104., 100., 101., 105., 107., 111., 112.,
       114., 107., 109., 115., 118., 112., 111., 108., 106., 114., 112.,
        99.,  95.,  93., 105., 120., 110., 115., 115., 103., 106., 107.,
       108., 109., 106.,  97.,  98.,  97.,  99., 100., 100., 120., 119.,
       113., 107., 105., 106., 104., 112., 110., 111., 117., 116., 103.,
       108., 109., 107., 110., 105., 106., 102., 104.,  99., 104., 117.,
       119., 106., 108., 106., 100., 113., 112., 112., 118., 114., 105.,
       105., 112., 113., 109., 103., 100., 116., 109., 110., 118., 115.,
       120., 112., 113., 105., 114., 116., 106., 11

In [9]:
Chance_of_Admit

array([0.92, 0.76, 0.72, 0.8 , 0.65, 0.9 , 0.75, 0.68, 0.5 , 0.45, 0.52,
       0.84, 0.78, 0.62, 0.61, 0.54, 0.66, 0.65, 0.63, 0.62, 0.64, 0.7 ,
       0.94, 0.95, 0.97, 0.94, 0.76, 0.44, 0.46, 0.54, 0.65, 0.74, 0.91,
       0.9 , 0.94, 0.88, 0.64, 0.58, 0.52, 0.48, 0.46, 0.49, 0.53, 0.87,
       0.91, 0.88, 0.86, 0.89, 0.82, 0.78, 0.76, 0.56, 0.78, 0.72, 0.7 ,
       0.64, 0.64, 0.46, 0.36, 0.42, 0.48, 0.47, 0.54, 0.56, 0.52, 0.55,
       0.61, 0.57, 0.68, 0.78, 0.94, 0.96, 0.93, 0.84, 0.74, 0.72, 0.74,
       0.64, 0.44, 0.46, 0.5 , 0.96, 0.92, 0.92, 0.94, 0.76, 0.72, 0.66,
       0.64, 0.74, 0.64, 0.38, 0.34, 0.44, 0.36, 0.42, 0.48, 0.86, 0.9 ,
       0.79, 0.71, 0.64, 0.62, 0.57, 0.74, 0.69, 0.87, 0.91, 0.93, 0.68,
       0.61, 0.69, 0.62, 0.72, 0.59, 0.66, 0.56, 0.45, 0.47, 0.71, 0.94,
       0.94, 0.57, 0.61, 0.57, 0.64, 0.85, 0.78, 0.84, 0.92, 0.96, 0.77,
       0.71, 0.79, 0.89, 0.82, 0.76, 0.71, 0.8 , 0.78, 0.84, 0.9 , 0.92,
       0.97, 0.8 , 0.81, 0.75, 0.83, 0.96, 0.79, 0.

In [10]:
admission_chance = Chance_of_Admit[TOEFL_score>110]  #putting the condition 
admission_chance_in_percentage = admission_chance * 100  #percentage
admission_chance_in_percentage 

array([92., 90., 84., 78., 70., 94., 95., 97., 94., 91., 90., 94., 87.,
       91., 86., 89., 78., 78., 72., 52., 55., 61., 78., 94., 96., 93.,
       72., 74., 96., 92., 94., 86., 90., 79., 74., 87., 91., 93., 94.,
       94., 85., 78., 84., 92., 96., 79., 89., 80., 90., 92., 97., 80.,
       81., 83., 96., 93., 94., 86., 81., 89., 89., 87., 85., 90., 89.,
       93., 93., 88., 90., 86., 94., 97., 97., 95., 96., 94., 93., 91.,
       76., 71., 82., 91., 88., 85., 86., 70., 76., 77., 93., 85., 90.,
       70., 83., 89., 80., 94., 93., 92., 89., 86., 90., 71., 80., 79.,
       80., 81., 80., 80., 83., 94., 93., 91., 86., 95., 96., 96., 84.,
       89., 91., 95.])

# TASK 5

In [11]:
research_experience = adm_data[:,7]  #Calling research_experience column as 1D
serial_no = adm_data[:,0]            #calling serial_no column as 1D

scholarship_eligible = serial_no[(research_experience== 1)&(GRE_score > 315)& (TOEFL_score >115)] #putting the condition
print("\nTotal No.of Students Eligible for $1000 Scholarship is:",scholarship_eligible.size)  #count of total no.of eligible Students
print("\nserial_no of eligible students are:",scholarship_eligible)  #serial_no of eligible students


Total No.of Students Eligible for $1000 Scholarship is: 41

serial_no of eligible students are: [  1.  23.  24.  25.  26.  33.  53.  71.  82.  98.  99. 108. 109. 121.
 122. 130. 139. 142. 144. 149. 152. 172. 177. 188. 194. 203. 204. 213.
 214. 215. 216. 260. 286. 287. 326. 338. 362. 373. 386. 398. 400.]
